name: dserver-client-container-image-build-and-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pip-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pip-tools and pipdeptree
        run: |
          pip install --upgrade pip
          pip install wheel setuptools_scm
          pip install pip-tools
          pip install pipdeptree
          
      - name: Requirements inspection and upgrade
        run: |
          cd compose/production/dserver_client
          echo "### Initial pip install -r requirements.txt ###"
          pip install -r requirements.txt
          echo "### Initial pipdeptree ###"
          pipdeptree | tee pipdeptree.initial
          echo "### pip-compile --upgrade ###"
          pip-compile --upgrade requirements.in
          echo "### requirements.txt diff ###"
          git diff requirements.txt | tee diff_requirements.txt
          echo "### Repeated pip install -r requirements.txt ###"
          pip install -r requirements.txt
          echo "### Upgraded pipdeptree ###"
          pipdeptree | tee pipdeptree.upgraded

  build-and-test:
    uses: livMatS/dtool-framework-workflows/.github/workflows/dtool-lookup-framework-generic-container-image-build-and-test.yml@main
    with:
      image: jotelha/dserver-client
      service: dserver_client
      docker_file: ./compose/production/dserver_client/Dockerfile
